### PR TITLE
RTL-TCP patches by Krzystof Halasa

### PR DESCRIPTION
**Pull request by andreer**
Found these here: http://lists.osmocom.org/pipermail/osmocom-sdr/2016-August/001480.html, for me this fixes https://github.com/csete/gqrx/issues/99

### CODE REVIEW

**Comment by csete** [comment]
Thanks, but this patch seems to be doing much more than fixing that issue, so merging is not feasible. Having many small patches that fix one particular issue is much preferred over one large patch that fixes many thing.

**Comment by csete** [comment]
Thanks. I will review the patches when I have time to work on gqrx, but please understand that this is not and official repository in any way and I only use it to keep track of patches that I may or may not include in the Ubuntu packages.

**Comment by andreer** [comment]
Sure, just wanted to make it easier for you if you did want to include them. And thanks for making GQRX, it's my favourite SDR app so far :-)

**Comment by csete** [comment]
Ok, I'm merging it to the rtlsdr branch.

I prefer to keep the master branch the same as upstream and have various patches in branches with one branch per device.

**Pull request merged**
