### PR TITLE
Added Hostname instead of IP, increased buffersize -> 6MSps working w…

### PR DESCRIPTION
**Pull request by steffen-g**
- Using the hostname instead of the IP
- Increased buffersize allows up to 6Msps over Realtek USB Ethernet adapter
- Changed gain settings, manual is working if uncommented
- Using Pluto_source and removed short to float and complex converters

### CODE REVIEW

**Comment by csete** [comment]
The latest code is in the plutosdr branch.

Last time I tried, pluto.local didn't work for me. Does it require some special network setup?

We can play with the buffer size, but I wonder if it should be something derived fromt the sample rate. Large buffer will increase latency at lower rates.

**Comment by csete** [comment]
Also just for the record, this is not the official gr-osmosdr repository and I only use it for keeping my own patches that I include in the Ubuntu packages. They disappear once the patchers are merged upstream.

**Comment by csete** [comment]
Ok, so pluto.local works for me too now, but the large buffer really ruins the low sample rates e.g. 600k. You can see how the waterfall looses its teporal resolution because the large buffer results in few transfers per second:

screenshot_745

Same problem with rtl-sdr, so we just probably need to adjust the buffer size as a function of sample rate. To begin with we can just use the two values if you find out when it is necessary to switch to the large buffer.

**Comment by steffen-g** [comment]
Hi,

I know this is not the official gr-osmosdr repository, but I wanted to share what I found out so far, as it might be helpful for others. And I have somehow not seen the plutosdr branch.

Using the hostname pluto.local might require running avahi on Linux, I haven't tested it on windows.

I have tested which buffer size results in the highest data rate using the iio_readdev tool. You are right, a large buffer will result in a large delay when using low sample rates. Next step I would try is to set the buffer size dynamically depending on the sample rate. Maybe setting the delay to 50 ms and calculating the buffer size, I will test this as soon as I have the time.

**Comment by csete** [comment]
Like I said, we don't have to find the optimal buffers over the whole range. The default appears to work fine at the lowest rate (without decimation), so finding at which rate we need to increase the buffer size can be sufficient for now.

**Comment by csete** [comment]
Looks like the PR was closed automatically because I deleted the iiodev branch.

Anyway, I have changed the default URI to ip:pluto.local and added the option to specify the URI in the device string. I haven't figured out how to use wildcards in the USB URI.

We can also add the buffer size or the number of buffers as a device string option.

**Comment by KeyserSoze1** [comment]
I'll throw in my observations.  3 Msps works with the existing buffers.  4 Msps starts to drop samples.  Using a 250k buffer appears to be successful at 5 Msps with a usb gigabit adapter.

**Comment by KeyserSoze1** [comment]
Success with 6 Msps and 500k buffer.  7 Msps has not been successful for me even increasing the buffer size to 1000k.

**Comment by KeyserSoze1** [comment]
Sorry.  Wanted to check back and report that I was incorrect and 6 Msps was not without dropped samples.  So it appears 5 Msps is the max achievable that I have found.

**Pull request closed without merging**
